name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.2
        with:
          username: ${{ secrets.SSH_USERNAME }}
          server: ${{ secrets.SSH_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          remote_path: ${{ secrets.SSH_ROOT }}

      - name: Reload Server
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          command: nfsn signal-daemon server HUP
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
